- name: Installing MySQL repository.
  yum: name=http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm state=present

- name: Installing mysql-community-client
  yum: pkg=mysql-community-client state=latest

- name: Install mysql-router
  yum: pkg=mysql-router state=latest

- name: Install expect (required for the mysqlrouterd service)
  yum: pkg=expect state=latest

- name: Install the mysqlrouterd service init script.
  copy: src=etc/init.d/mysqlrouterd dest=/etc/init.d/mysqlrouterd mode=0544

- name: Install the mysqlrouterd service configuration.
  copy: src={{mysqlrouterd_sysconfig}} dest=/etc/sysconfig/mysqlrouterd mode=0400

- name: Ensure /etc/mysqlrouterd dir exists
  file: path=/etc/mysqlrouterd state=directory

- name: Install the mysqlrouterd deamon script.
  copy: src=etc/mysqlrouterd/daemon dest=/etc/mysqlrouterd/daemon mode=0544

- name: Install the mysqlrouter configuration.
  copy: src={{mysqlrouter_ini}} dest=/etc/mysqlrouter/mysqlrouter.ini mode=0400

- name: Start the mysqlrouterd service
  service: name=mysqlrouterd state=started enabled=yes