- name: Disabling the fastestmirror yum plugin.
  copy: src=etc/yum/pluginconf.d/fastestmirror.conf dest=/etc/yum/pluginconf.d/fastestmirror.conf

- name: Stopping iptables
  service: name=iptables state=stopped enabled=no
