- name: initiate the initial cluster synchronization
  command: drbdadm -- --overwrite-data-of-peer primary clusterdb

- name: format drbd partition
  filesystem: fstype=ext4 opts="-Lclusterdb" dev=/dev/drbd0

- name: Disable checking of the clusterdb file system
  command: tune2fs -c 0 -i 0 /dev/drbd0

- name: mount clusterdb partition to mysql fabric-master data directory (/var/lib/mysql-fabric-master)
  mount: name=/var/lib/mysql-fabric-master fstype=ext4 opts=noatime src=/dev/drbd0 state=mounted

- name: Ensure mysql-fabric-master data dir exists
  file: path=/var/lib/mysql-fabric-master/data state=directory

- name: Set permissions on the mysql-fabric-master data dir to mysql
  file: path=/var/lib/mysql-fabric-master/data owner=mysql group=mysql

# pacemaker needs this config file to be only readable by the owner.
- name: Add the fabric.cfg file.
  copy: src=mysql-fabric-master/fabric.cfg dest=/var/lib/mysql-fabric-master/fabric.cfg mode=0400

- name: Adding the /etc/my.cnf file.
  template: src=mysql-fabric-master/my.cnf.t dest=/var/lib/mysql-fabric-master/my.cnf

- name: Turn off quorum policy as we only have 2 nodes
  command: crm configure property no-quorum-policy=ignore

- name: Turn off stonith as we only have 2 nodes
  command: crm configure property stonith-enabled=false

- name: Configure resource stickiness for corosync
  command: crm configure rsc_defaults resource-stickiness=100


