- name: Add the drbd resource file.
  template: src={{drbd_resource_template}} dest=/etc/drbd.d/{{drbd_resource_name}}.res

- name: Check if the drbd clusterdb resource is already created.
  command: drbdadm dump-md clusterdb
  ignore_errors: True
  register: md_status

- name: Create the drbd clusterdb resource
  command: drbdadm create-md clusterdb
  when: md_status.rc == 255

- name: Install the pacemaker mysql-fabric resource
  copy: src=ocf/mysql-fabric dest=/usr/lib/ocf/resource.d/heartbeat/mysql-fabric mode=0755

- name: Install the mysql-fabric-master service script
  copy: src=etc/init.d/mysql-fabric-master dest=/etc/init.d/mysql-fabric-master mode=0755

- name: Install the mysql-fabric-master sysconfig settings
  copy: src=etc/sysconfig/mysql-fabric-master dest=/etc/sysconfig/mysql-fabric-master

- name: Remove the default mysql-fabric config file. Our one will be added by the primary node.
  file: path=/etc/mysql/fabric.cfg state=absent
