- name: Start drbd
  service: name=drbd state=started enabled=no

- name: Check the status of the clusterdb resource
  command: drbdadm dstate clusterdb
  register: drbd_status

- name: Attach the drbd clusterdb resource
  command: drbdadm attach clusterdb
  when: (drbd_status.stdout.split('/')[0].find('Diskless') != -1) or (drbd_status.stdout.split('/')[0].find('Unconfigured') != -1)

- name: Sync the drbd clusterdb resource
  command: drbdadm syncer clusterdb

- name: Recheck the status of the clusterdb resource
  command: drbdadm cstate clusterdb
  register: drbd_status

- name: Connect the drbd clusterdb resource nodes
  command: drbdadm connect clusterdb
  when: drbd_status.stdout.find('StandAlone') != -1

- name: Ensure mysql-fabric-master mount point exists
  file: path=/var/lib/mysql-fabric-master state=directory

- name: Set permissions on the mysql-fabric-master mount point to mysql
  file: path=/var/lib/mysql-fabric-master owner=mysql group=mysql
