# This is needed by the mysql_user ansible command.
- name: Installing MySQL-python
  yum: pkg=MySQL-python state=latest

- name: Set the Mysql server id
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=server-id
            value={{ server_id }}

# We need to enable binary logging only after adding the user, due to http://bugs.mysql.com/bug.php?id=72281.
- name: Disable Mysql Binary logging
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=log_bin
            state=absent

- name: Disable Mysql GTID mode as it can only be used with bin logging
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=gtid-mode
            value=OFF

# This will install the database as well if it doesn't exist. We want to start it, but not enable it, because it's the
# cluster's job to enable it as appropriate.
- name: (Re)start the MySQL service
  service: name=mysqld state=started enabled=false

# MySQL Fabric uses the 'fabric_slave' user account to access all MySQL servers that it will manage.
# In other words, the 'fabric_slave' user must be created on all slave MySQL servers
- name: Adding slave mysql user
  mysql_user:
    login_host: '127.0.0.1'
    login_port: 3306
    login_user: root
    login_password: ""
    name: "{{fabric_slave_mysql_user}}"
    host: "{{fabric_slave_subnet}}"
    password: "{{fabric_slave_mysql_pass}}"
    priv: "mysql_fabric.*:ALTER,CREATE,DELETE,DROP,INSERT,SELECT,UPDATE/*.*:DELETE,PROCESS,RELOAD,REPLICATION CLIENT,REPLICATION SLAVE,SELECT,SUPER,TRIGGER"
    state: present

# We need to enable binary logging only after adding the user, due to http://bugs.mysql.com/bug.php?id=72281.
- name: Enable Mysql Binary logging
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=log_bin
            value=mysql-bin

- name: Set Mysql Binary logging format
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=binlog_format
            value=ROW

- name: Enable Mysql GTID mode
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=gtid-mode
            value=ON

- name: Enforce Mysql GTID consistency
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=enforce-gtid-consistency
            value=true

- name: Log Mysql slave updates
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=log_slave_updates
            value=true

- name: Skip starting Mysql slaves
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=skip-slave-start
            value=true

- name: Write master connection info to tables, not files
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=master-info-repository
            value=TABLE

- name: Write relay log info to tables, not files
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=relay-log-info-repository
            value=TABLE

- name: Setup relay log binary
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=relay-log
            value=mysqld-relay-bin

- name: Restart the MySQL service
  service: name=mysqld state=restarted