- name: Enable Mysql Binary logging
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=log_bin
            value=mysql-bin

- name: Set Mysql Binary logging format
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=binlog_format
            value=ROW

- name: Enable Mysql GTID mode
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=gtid-mode
            value=ON

- name: Enforce Mysql GTID consistency
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=enforce-gtid-consistency
            value=true

- name: Log Mysql slave updates
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=log_slave_updates
            value=true

- name: Skip starting Mysql slaves
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=skip-slave-start
            value=true

# This will install the database as well if it doesn't exist.
- name: Start the mysql instance
  service: name=mysqld state=restarted enabled=yes

# MySQL Fabric uses the 'fabric_slave' user account to access all MySQL servers that it will manage.
# In other words, the 'fabric_slave' user must be created on all slave MySQL servers
- name: Adding slave mysql user
  mysql_user:
    login_host: '127.0.0.1'
    login_port: 3306
    login_user: root
    login_password: ""
    name: fabric_slave
    host: 192.168.70.0/255.255.255.0
    password: f4bric
    priv: "mysql_fabric.*:ALTER,CREATE,DELETE,DROP,INSERT,SELECT,UPDATE/*.*:DELETE,PROCESS,RELOAD,REPLICATION CLIENT,REPLICATION SLAVE,SELECT,SUPER,TRIGGER"
    state: present
