- name: Disable binary logging
  copy: src=templates/etc/mysql.d/disable_binary_log.cnf dest=/etc/my.cnf.d/disable_binary_log.cnf owner=root group=root mode=0644

- name: Restart the MySQL service
  service: name=mysqld state=restarted

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db: name=test
            state=absent
            login_user=root
            login_password=""

- name: Enable binary logging
  file: path=/etc/my.cnf.d/disable_binary_log.conf state=absent

- name: Restart the MySQL service
  service: name=mysqld state=restarted