- name: ensure corosync is running (and automatically at boot time)
  service: name=corosync state=started enabled=yes

- name: ensure Pacemaker is running (and automatically at boot time)
  service: name=pacemaker state=started enabled=yes
