- name: Install DRBD utilities
  yum: name=drbd83-utils state=latest

- name: Install DRBD kernel module
  yum: name=kmod-drbd83 state=latest

- name: Install Service runlevel configuration tool (ntsysv)
  yum: name=ntsysv state=latest

- name: Install Asynchronous IO library (libaio)
  yum: name=libaio state=latest
